# Tahap build aplikasi Node.js
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Tahap nginx dengan konfigurasi HTTPS dan rate limiting
FROM nginx:alpine

# Install openssl untuk generate sertifikat
RUN apk add --no-cache openssl

# Buat direktori sertifikat
#RUN mkdir -p /etc/ssl/certs /etc/ssl/private

#RUN openssl req -x509 -nodes -days 365 \
#    -subj "/CN=coba.com/O=Your Company/C=ID" \
#    -newkey rsa:2048 \
#    -keyout /etc/ssl/private/dummy_key.pem \
#    -out /etc/ssl/certs/dummy_cert.pem

RUN mkdir -p /etc/ssl/certs /etc/ssl/private && \
    openssl req -x509 -nodes -days 365 \
    -subj "/CN=coba.com/O=YourCompany/C=ID" \
    -newkey rsa:2048 \
    -keyout /etc/ssl/private/dummy_key.pem \
    -out /etc/ssl/certs/dummy_cert.pem

COPY dhparam.pem /etc/ssl/certs/dhparam.pem

# Salin hasil build aplikasi ke nginx html folder
COPY --from=build /app/build /usr/share/nginx/html

# Salin file konfigurasi nginx ke container
COPY nginx.conf.https8 /etc/nginx/nginx.conf

EXPOSE 80 
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
