apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: laravel
        image: 192.168.140.32:8003/sini/laravel:1.0  # Sesuai Harbor Anda
        ports:
        - containerPort: 8001
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "laravel"
        - name: DB_USERNAME
          value: "laravel"
        - name: DB_USER
          value: "laravel"
        - name: DB_PASSWORD
          value: "qwerty12"
        - name: DB_NAME
          value: "laravel"
        - name: APP_KEY
          value: "base64:your-app-key-here"
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: RUN_MIGRATIONS
          value: "true"
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 120
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30082
  type: NodePort
